export const ENGINE_ERROR_CREATING_CANVAS_2D_CONTEXT = 'ENGINE_ERROR_CREATING_CANVAS_2D_CONTEXT';
export const ENGINE_ERROR_CREATING_WEBGL_CONTEXT = 'ENGINE_ERROR_CREATING_WEBGL_CONTEXT';
export const ENGINE_ERROR_WEBGL_CONTEXT_LOST = 'ENGINE_ERROR_WEBGL_CONTEXT_LOST';
export const ENGINE_ERROR_GETTING_DOCUMENT = 'ENGINE_ERROR_GETTING_DOCUMENT';
export const ENGINE_ERROR_INVALID_BITMAP_FONT_ATLAS = 'ENGINE_ERROR_INVALID_BITMAP_FONT_ATLAS';
export const ENGINE_ERROR_CREATING_AUDIO_CONTEXT = 'ENGINE_ERROR_CREATING_AUDIO_CONTEXT';
export const ENGINE_ERROR_CANNOT_SET_FRAME = 'ENGINE_ERROR_CANNOT_SET_FRAME';
export const ENGINE_ERROR_CANNOT_SET_FRAME_NAME = 'ENGINE_ERROR_CANNOT_SET_FRAME_NAME';
