export class EventManager {
    constructor(sprite: any);
    parent: any;
    _onAddedToGroup: Signal;
    _onRemovedFromGroup: Signal;
    _onDestroy: Signal;
    _onOutOfBounds: Signal;
    _onEnterBounds: Signal;
    _onInputOver: Signal;
    _onInputOut: Signal;
    _onInputDown: Signal;
    _onInputUp: Signal;
    _onDragStart: Signal;
    _onDragUpdate: Signal;
    _onDragStop: Signal;
    _onAnimationStart: Signal;
    _onAnimationComplete: Signal;
    _onAnimationLoop: Signal;
    destroy(): void;
    _parent: any;
    get onAddedToGroup(): Signal;
    onAddedToGroup$dispatch(...args: any[]): void;
    get onRemovedFromGroup(): Signal;
    onRemovedFromGroup$dispatch(...args: any[]): void;
    get onDestroy(): Signal;
    onDestroy$dispatch(...args: any[]): void;
    get onOutOfBounds(): Signal;
    onOutOfBounds$dispatch(...args: any[]): void;
    get onEnterBounds(): Signal;
    onEnterBounds$dispatch(...args: any[]): void;
    get onInputOver(): Signal;
    onInputOver$dispatch(...args: any[]): void;
    get onInputOut(): Signal;
    onInputOut$dispatch(...args: any[]): void;
    get onInputDown(): Signal;
    onInputDown$dispatch(...args: any[]): void;
    get onInputUp(): Signal;
    onInputUp$dispatch(...args: any[]): void;
    get onDragStart(): Signal;
    onDragStart$dispatch(...args: any[]): void;
    get onDragUpdate(): Signal;
    onDragUpdate$dispatch(...args: any[]): void;
    get onDragStop(): Signal;
    onDragStop$dispatch(...args: any[]): void;
    get onAnimationStart(): Signal;
    onAnimationStart$dispatch(...args: any[]): void;
    get onAnimationComplete(): Signal;
    onAnimationComplete$dispatch(...args: any[]): void;
    get onAnimationLoop(): Signal;
    onAnimationLoop$dispatch(...args: any[]): void;
}
import { Signal } from './signal';
//# sourceMappingURL=event_manager.d.ts.map