export class Game {
    constructor(gameConfig?: {});
    config: {};
    id: number;
    parent: string;
    width: number;
    height: number;
    renderer: CanvasRenderer | WebGLRenderer;
    state: SceneManager;
    isBooted: boolean;
    raf: RequestAnimationFrame;
    add: GameObjectFactory;
    cache: Cache;
    input: Input;
    load: Loader;
    scale: ScaleManager;
    sound: SoundManager;
    stage: Stage;
    time: Time;
    tweens: TweenManager;
    world: World;
    device: Device;
    canvas: any;
    context: any;
    onPause: Signal;
    onResume: Signal;
    onBoot: Signal;
    isPaused: boolean;
    boot(): void;
    initRenderer(): void;
    contextLostBinded: (event: any) => void;
    contextRestoredBinded: () => void;
    parseConfigElement(config: any, key: any, defaultValue: any): void;
    parseConfig(config: any): void;
    exceptionHandler: any;
    contextLost(event: any): void;
    contextRestored(): void;
    update(time: any): void;
    destroy(): void;
}
import { CanvasRenderer } from '../display/canvas/renderer';
import { WebGLRenderer } from '../display/webgl/renderer';
import { SceneManager } from './scene_manager';
import { RequestAnimationFrame } from './raf';
import { GameObjectFactory } from './factory';
import { Cache } from './cache';
import { Input } from './input';
import { Loader } from './loader';
import { ScaleManager } from './scale_manager';
import { SoundManager } from './sound_manager';
import { Stage } from './stage';
import { Time } from './time';
import { TweenManager } from './tween_manager';
import { World } from './world';
import { Device } from './device';
import { Signal } from './signal';
//# sourceMappingURL=game.d.ts.map