export class Input {
    constructor(game: any);
    game: any;
    hitCanvas: any;
    hitContext: any;
    moveCallbacks: any[];
    lockCallbacks: any[];
    customCandidateHandler: any;
    customCandidateHandlerContext: any;
    pollRate: number;
    enabled: boolean;
    multiInputOverride: number;
    position: Point;
    speed: Point;
    circle: Circle;
    scale: Point;
    maxPointers: number;
    tapRate: number;
    doubleTapRate: number;
    holdRate: number;
    justPressedRate: number;
    justReleasedRate: number;
    recordPointerHistory: boolean;
    recordRate: number;
    recordLimit: number;
    pointer1: any;
    pointer2: any;
    pointer3: any;
    pointer4: any;
    pointer5: any;
    pointer6: any;
    pointer7: any;
    pointer8: any;
    pointer9: any;
    pointer10: any;
    pointers: any[];
    activePointer: Pointer;
    mousePointer: Pointer;
    mouse: Mouse;
    touch: Touch;
    mspointer: MSPointer;
    resetLocked: boolean;
    onDown: Signal;
    onUp: Signal;
    onTap: Signal;
    onHold: Signal;
    minPriorityID: number;
    interactiveItems: ArraySet;
    _localPoint: Point;
    _pollCounter: number;
    _oldPosition: Point;
    _x: number;
    _y: number;
    boot(): void;
    _onClickTrampoline: (event: any) => void;
    destroy(): void;
    setInteractiveCandidateHandler(callback: any, context: any): void;
    addMoveCallback(callback: any, context: any): void;
    deleteMoveCallback(callback: any, context: any): void;
    addPointer(): Pointer;
    update(): void;
    reset(hard?: boolean): void;
    resetSpeed(x: any, y: any): void;
    startPointer(event: any): any;
    updatePointer(event: any): any;
    stopPointer(event: any): any;
    countActivePointers(limit?: number): number;
    getPointer(isActive?: boolean): any;
    getPointerFromIdentifier(identifier: any): any;
    getPointerFromId(pointerId: any): any;
    getLocalPosition(displayObject: any, pointer: any, output?: any): any;
    hitTest(displayObject: any, pointer: any, localPoint: any): any;
    onClickTrampoline(): void;
    set x(arg: number);
    get x(): number;
    set y(arg: number);
    get y(): number;
    get pollLocked(): boolean;
    get totalInactivePointers(): number;
    get totalActivePointers(): number;
    get worldX(): number;
    get worldY(): number;
}
import { Point } from '../geom/point';
import { Circle } from '../geom/circle';
import { Pointer } from './input_pointer';
import { Mouse } from './input_mouse';
import { Touch } from './input_touch';
import { MSPointer } from './input_mspointer';
import { Signal } from './signal';
import { ArraySet } from './array_set';
//# sourceMappingURL=input.d.ts.map