export default class _default {
    constructor(game: any);
    game: any;
    cache: any;
    isLoading: boolean;
    isUseLog: boolean;
    isUseRetry: boolean;
    maxRetry: number;
    hasLoaded: boolean;
    preloadSprite: {
        sprite: any;
        direction: number;
        width: any;
        height: any;
        rect: null;
    } | null;
    crossOrigin: boolean;
    baseURL: string;
    path: string;
    headers: {
        requestedWith: boolean;
        json: string;
        xml: string;
    };
    onLoadStart: Signal;
    onLoadComplete: Signal;
    onPackComplete: Signal;
    onFileStart: Signal;
    onFileComplete: Signal;
    onFileError: Signal;
    maxParallelDownloads: any;
    _withSyncPointDepth: number;
    _fileList: any[];
    _flightQueue: any[];
    _processingHead: number;
    _fileLoadStarted: boolean;
    _totalPackCount: number;
    _totalFileCount: number;
    _loadedPackCount: number;
    _loadedFileCount: number;
    setPreloadSprite(sprite: any, direction?: number): void;
    resize(): void;
    checkKeyExists(type: any, key: any): boolean;
    getAssetIndex(type: any, key: any): number;
    getAsset(type: any, key: any): {
        index: number;
        file: any;
    } | null;
    reset(hard: any, clearEvents?: boolean): void;
    addToFileList(type: any, key?: string, url?: null, properties?: null, overwrite?: boolean, extension?: null): default;
    replaceInFileList(type: any, key: any, url: any, properties: any): default;
    pack(key: any, url: any, data: any, callbackContext: any): default;
    image(key: any, url: any, overwrite: any): default;
    images(keys: any, urls: any): default;
    text(key: any, url: any, overwrite: any): default;
    json(key: any, url: any, overwrite: any): default;
    xml(key: any, url: any, overwrite: any): default;
    spritesheet(key: any, url: any, frameWidth: any, frameHeight: any, frameMax?: number, margin?: number, spacing?: number): default;
    audio(key: any, urls: any, autoDecode?: boolean): default;
    audioSprite(key: any, urls: any, jsonURL: any, jsonData: any, autoDecode?: boolean): default;
    bitmapFont(key: any, textureURL?: null, atlasURL?: null, atlasData?: null, xSpacing?: number, ySpacing?: number): default;
    atlas(key: any, textureURL: any, atlasURL?: null, atlasData?: null, format?: number): default;
    withSyncPoint(callback: any, callbackContext: any): default;
    addSyncPoint(type: any, key: any): default;
    removeFile(type: any, key: any): void;
    removeAll(): void;
    start(): void;
    processLoadQueue(): void;
    finishedLoading(abnormal: any): void;
    asyncComplete(file: any, errorMessage?: string): void;
    processPack(pack: any): void;
    transformUrl(url: any, file: any): any;
    loadFile(file: any): void;
    loadImageTag(file: any): void;
    xhrLoad(file: any, url: any, type: any, onload: any, onerror: any): void;
    xhrLoadWithXDR(): void;
    getAudioURL(urls: any): any;
    fileError(file: any, xhr: any, reason: any): void;
    fileComplete(file: any, xhr: any): void;
    jsonLoadComplete(file: any, xhr: any): void;
    csvLoadComplete(): void;
    xmlLoadComplete(file: any, xhr: any): void;
    parseXml(data: any): any;
    updateProgress(): void;
    log(message: any, data?: string): void;
    totalLoadedFiles(): number;
    totalQueuedFiles(): number;
    totalLoadedPacks(): number;
    totalQueuedPacks(): number;
    get progressFloat(): number;
    get progress(): number;
}
import Signal from './signal';
//# sourceMappingURL=loader.d.ts.map