export default class _default {
    constructor(game: any, key: any, volume?: number, loop?: boolean, connect?: null);
    game: any;
    name: any;
    key: any;
    loop: boolean;
    markers: {};
    context: any;
    autoplay: boolean;
    totalDuration: number;
    startTime: number;
    currentTime: number;
    duration: number;
    durationMS: number;
    position: number;
    stopTime: number;
    paused: boolean;
    pausedPosition: number;
    pausedTime: number;
    isPlaying: boolean;
    currentMarker: string;
    fadeTween: any;
    pendingPlayback: boolean;
    override: boolean;
    allowMultiple: boolean;
    externalNode: any;
    masterGainNode: any;
    gainNode: any;
    _sound: any;
    _markedToDelete: boolean;
    _removeFromSoundManager: boolean;
    onPlay: Signal;
    onPause: Signal;
    onResume: Signal;
    onLoop: Signal;
    onStop: Signal;
    onMute: Signal;
    onMarkerComplete: Signal;
    onFadeComplete: Signal;
    _volume: number;
    _buffer: any;
    _muted: boolean;
    _tempMarker: number;
    _tempPosition: number;
    _tempVolume: number;
    _tempPause: number;
    _muteVolume: number;
    _tempLoop: number;
    _paused: boolean;
    soundHasUnlocked(key: any): void;
    addMarker(name: any, start: any, duration?: number, volume?: number, loop?: boolean): void;
    removeMarker(name: any): void;
    onEndedHandler(): void;
    update(): void;
    loopFull(volume: any): default;
    play(marker: any, position: any, volume: any, loop: any, forceRestart: any): default;
    set volume(arg: number);
    get volume(): number;
    restart(marker?: string, position?: number, volume?: number, loop?: boolean): void;
    pause(): void;
    resume(): void;
    stop(): void;
    fadeIn(duration: any, loop?: boolean, marker?: string): void;
    fadeOut(duration: any): void;
    fadeTo(duration?: number, volume?: number): void;
    fadeComplete(): void;
    destroy(remove?: boolean): void;
    set mute(arg: any);
    get mute(): any;
}
import Signal from './signal';
//# sourceMappingURL=sound.d.ts.map