export function add(a: Point, b: Point, output?: Point): Point;
export function subtract(a: Point, b: Point, output?: Point): Point;
export function multiply(a: Point, b: Point, output?: Point): Point;
export function divide(a: Point, b: Point, output?: Point): Point;
export function equals(a: Point, b: Point): boolean;
export function angle(a: Point, b: Point): number;
export function negative(a: Point, output?: Point): Point;
export function multiplyAdd(a: Point, b: Point, s: number, output?: Point): Point;
export function interpolate(a: Point, b: Point, f: number, output?: Point): Point;
export function perp(a: Point, output?: Point): Point;
export function rperp(a: Point, output?: Point): Point;
export function distance(a: Point, b: Point, round?: boolean): number;
export function project(a: Point, b: Point, output?: Point): Point;
export function projectUnit(a: Point, b: Point, output?: Point): Point;
export function normalRightHand(a: Point, output?: Point): Point;
export function normalize(a: Point, output?: Point): Point;
export function rotate(a: Point, x: number, y: number, ang: number, asDegrees: boolean, dist: number): object;
export function centroid(points: Point[], output?: Point): Point;
export function parse(obj: object, xProp?: string, yProp?: string): Point;
export function clone(input: Point, output?: Point): Point;
import { Point } from '../point.js';
//# sourceMappingURL=point.d.ts.map